apiVersion: v1
kind: Secret
metadata:
  name: {{ include "teams-relay.fullname" . }}
  labels:
    {{- include "teams-relay.labels" . | nindent 4 }}
type: Opaque
stringData:
  BOT_TENANT_ID: {{ .Values.config.bot.tenantId | quote }}
  BOT_APP_ID: {{ .Values.config.bot.appId | quote }}
  BOT_APP_PASSWORD: {{ .Values.config.bot.appPassword | quote }}
  WEBHOOK_TOKENS: {{ .Values.config.webhookTokens | quote }}
  DYNAMODB_TABLE: {{ .Values.config.dynamodb.table | quote }}
  DYNAMODB_REGION: {{ .Values.config.dynamodb.region | quote }}
